// Writes the wrangler config that deploy-cloudflare deploys with:
//
//   node write-config.js <file> <worker-name> <assets-directory>
//
// Generated per run rather than committed per repo, so consumers stay
// config-free. Paths in a wrangler config resolve against the config file,
// which lives in RUNNER_TEMP, so the assets directory must be absolute.
//
// The action harness runs this same file through the pinned wrangler with
// --dry-run, so a wrangler bump that stops accepting this shape fails CI
// rather than a consumer's deploy.
const fs = require("fs");
const path = require("path");

const [file, name, directory] = process.argv.slice(2);
if (!file || !name || !directory || !path.isAbsolute(directory)) {
  console.error("usage: node write-config.js <file> <worker-name> <absolute-assets-directory>");
  process.exit(2);
}

const config = {
  name,
  compatibility_date: "2026-09-01",
  assets: { directory },
  // The production URL the action constructs and probes.
  workers_dev: true,
  // Needed for `alias`. Previews sit behind the same Access application
  // when it is set to All traffic, and the alias is probed after upload.
  preview_urls: true,
};

fs.writeFileSync(
  file,
  "// Generated by quantecon/actions/deploy-cloudflare for one deploy.\n" +
    JSON.stringify(config, null, 2) + "\n"
);
