name: 'Setup LaTeX'
description: 'Installs LaTeX packages required for Jupyter Book PDF builds'
author: 'QuantEcon'

inputs:
  cache-version:
    description: 'Cache version for manual invalidation'
    required: false
    default: 'v1'
  latex-requirements-file:
    description: 'Path to latex-requirements.txt file listing packages to install'
    required: false
    default: 'latex-requirements.txt'
  packages:
    description: 'DEPRECATED: Use latex-requirements-file instead. Space-separated list of LaTeX packages (used as fallback)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # NOTE: LaTeX caching removed - system package installations at /usr/share/* 
    # cannot be reliably cached due to permission restrictions in GitHub Actions.
    # The ~2-3 minute installation time is unavoidable but acceptable.
    
    - name: Install LaTeX packages
      shell: bash
      run: |
        # Read packages from latex-requirements.txt (if it exists)
        if [ -f "${{ inputs.latex-requirements-file }}" ]; then
          echo "Reading packages from ${{ inputs.latex-requirements-file }}"
          # Remove comments and empty lines, join with spaces
          PACKAGES=$(grep -v '^#' "${{ inputs.latex-requirements-file }}" | grep -v '^[[:space:]]*$' | tr '\n' ' ')
          echo "Installing LaTeX packages: $PACKAGES"
          sudo apt-get update
          sudo apt-get install -y $PACKAGES
        elif [ -n "${{ inputs.packages }}" ]; then
          echo "Using deprecated packages input (migrate to latex-requirements.txt)"
          echo "Installing LaTeX packages: ${{ inputs.packages }}"
          sudo apt-get update
          sudo apt-get install -y ${{ inputs.packages }}
        else
          echo "Error: No packages specified. Provide either latex-requirements-file or packages input."
          exit 1
        fi
        
    - name: Display LaTeX Info
      shell: bash
      run: |
        echo "::group::LaTeX version"
        latex --version || echo "LaTeX not in PATH"
        pdflatex --version || echo "pdfLaTeX not in PATH"
        xelatex --version || echo "XeLaTeX not in PATH"
        echo "::endgroup::"
        echo "::notice::LaTeX packages installed (system packages cannot be cached)"

branding:
  icon: 'file-text'
  color: 'green'
