# Build Cache Generation Workflow (Container)
#
# Creates the build cache that ci.yml and publish.yml restore.
# A successful run saves a new cache; a failed run preserves the
# existing cache so PRs always have something to restore.
#
# Copy to your repository as .github/workflows/cache.yml
#
# Triggers:
#   - Weekly (Sunday midnight UTC) — fresh build with latest dependencies
#   - Manual dispatch — on-demand rebuild
#   - Push to main (environment.yml changes) — update cache after env change
#
# Action versions: Pin to @v1 for stability. Check for latest at:
#   https://github.com/quantecon/actions/releases

name: Build Cache

on:
  schedule:
    # Weekly on Sunday at midnight UTC
    - cron: '0 0 * * 0'

  workflow_dispatch:
    # Manual trigger for on-demand cache rebuild

  push:
    branches:
      - main
    paths:
      # Auto-rebuild when environment changes
      - 'environment.yml'

# Prevent concurrent cache builds — let prior run finish
concurrency:
  group: cache-build
  cancel-in-progress: false

jobs:
  build-cache:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quantecon/quantecon:latest
      # ─── Standard Runner Alternative ───────────────────────────────
      # Remove the 'container' block. The build-jupyter-cache action
      # calls setup-environment internally, which will install Conda
      # and (optionally) LaTeX on a standard runner.
      # ───────────────────────────────────────────────────────────────

    permissions:
      contents: read
      issues: write             # Required for auto-creating failure issues
      packages: read            # Required for container image pull

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build all requested formats and save cache.
      # Only saves if ALL builds succeed — preserves existing cache on failure.
      - name: Build and cache
        uses: quantecon/actions/build-jupyter-cache@v1
        with:
          # ─── Builders ──────────────────────────────────────────
          # Comma-separated list: html, jupyter, pdflatex
          # Each builder produces a cached _build/{format}/ directory.
          #
          #   html      — HTML site (always needed)
          #   jupyter   — .ipynb notebooks for download links
          #   pdflatex  — PDF for download link
          #
          # Start with 'html' and add formats as needed:
          builders: 'html'
          # builders: 'jupyter,html'             # HTML + notebook downloads
          # builders: 'jupyter,pdflatex,html'    # HTML + PDF + notebook downloads

          source-dir: 'lectures'

          # ─── Environment (container builds) ────────────────────
          # Only needed if you require packages beyond the container base.
          # environment-update: 'environment.yml'

          # ─── Environment (standard runner builds) ──────────────
          # environment: 'environment.yml'   # Full conda environment file

          # ─── Failure Handling ──────────────────────────────────
          create-issue-on-failure: 'true'
          # issue-assignees: 'maintainer1,maintainer2'
          # issue-labels: 'build-failure,automated'

          # ─── Artifacts ─────────────────────────────────────────
          upload-artifact: 'true'              # Upload _build for inspection
          artifact-retention-days: '30'
