# CI Workflow Template (Pull Request Preview)
#
# Provides fast PR feedback: restores cached builds, runs incremental HTML
# build, and deploys a Netlify preview with links to changed pages.
#
# Copy to your repository as .github/workflows/ci.yml
#
# Prerequisites:
#   1. cache.yml workflow running on schedule/main (generates the build cache)
#   2. Netlify site created for PR previews
#   3. Repository secrets: NETLIFY_AUTH_TOKEN, NETLIFY_SITE_ID
#
# Action versions: Pin to @v1 for stability. Check for latest at:
#   https://github.com/quantecon/actions/releases

name: CI

on:
  pull_request:
    branches:
      - main

# Cancel in-progress runs for the same PR
concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quantecon/quantecon:latest
      # ─── Standard Runner Alternative ───────────────────────────────
      # Remove the 'container' block above and uncomment the
      # setup-environment 'with' block below to run without a container.
      # This is slower (~7-8 min setup vs ~1-2 min) but has no
      # container dependency.
      # ───────────────────────────────────────────────────────────────

    permissions:
      contents: read
      pull-requests: write      # Required for PR preview comments
      packages: read            # Required for container image pull

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ─── Environment Setup ───────────────────────────────────────
      - name: Setup environment
        uses: quantecon/actions/setup-environment@v1
        # Container mode auto-detected — no setup needed unless you
        # have extra packages beyond the container's base environment.
        # with:
        #   environment-update: 'environment.yml'   # Delta packages for container
        #   install-latex: 'true'                    # Only needed for pdflatex builds
        #   latex-requirements-file: 'latex-requirements.txt'
        #
        # ─── Standard Runner (non-container) ──────────────────────
        # with:
        #   environment: 'environment.yml'    # Full conda environment
        #   python-version: '3.13'
        #   install-latex: 'true'

      # ─── Cache Restore ───────────────────────────────────────────
      # Restores the build cache generated by cache.yml on main.
      # This gives Jupyter Book pre-executed notebooks so the PR
      # build only re-runs changed content (seconds instead of hours).
      - name: Restore build cache
        uses: quantecon/actions/restore-jupyter-cache@v1
        with:
          cache-type: 'build'          # Full _build directory (default)
          # save-cache: 'true'         # Save updated cache scoped to this PR branch
          # fail-on-miss: 'false'      # Don't fail if no cache exists yet

      # ─── Build ───────────────────────────────────────────────────
      - name: Build lectures (HTML)
        uses: quantecon/actions/build-lectures@v1
        with:
          builder: 'html'
          source-dir: 'lectures'
          extra-args: '-W --keep-going'
          upload-failure-reports: 'true'    # Upload execution logs on failure
          # html-copy-pdf: 'true'           # Stage PDFs for download (requires prior pdflatex build)
          # html-copy-notebooks: 'true'     # Stage notebooks for download (requires prior jupyter build)

      # ─── PR Preview ──────────────────────────────────────────────
      # Deploys the built site to Netlify and posts a comment on the
      # PR with the preview URL and links to changed lecture pages.
      - name: Deploy PR preview
        uses: quantecon/actions/preview-netlify@v1
        with:
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: '_build/html'
          lectures-dir: 'lectures'   # Change detection for PR comment links

      # ─── Cloudflare Pages Alternative ────────────────────────────
      # Replace the Netlify step above with this to use Cloudflare Pages.
      # Secrets needed: CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID
      #
      # - name: Deploy PR preview
      #   uses: quantecon/actions/preview-cloudflare@v1
      #   with:
      #     cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     project-name: 'my-lecture-site'      # Cloudflare Pages project name
      #     build-dir: '_build/html'
      #     lectures-dir: 'lectures'
