name: 'Setup Environment'
description: 'Flexible environment setup - auto-detects container or installs Conda, LaTeX, and ML libraries'
author: 'QuantEcon'

inputs:
  python-version:
    description: 'Python version to use (ignored in container mode)'
    required: false
    default: '3.13'
  environment-file:
    description: 'Path to environment.yml for lecture-specific packages'
    required: false
    default: 'environment.yml'
  environment-name:
    description: 'Conda environment name (must match name in environment.yml)'
    required: false
    default: 'quantecon'
  cache-version:
    description: 'Cache version for manual invalidation (bump to force cache rebuild)'
    required: false
    default: 'v1'
  install-latex:
    description: 'Whether to install LaTeX packages (auto-disabled in container mode)'
    required: false
    default: 'false'
  latex-requirements-file:
    description: 'Path to latex-requirements.txt file listing packages to install'
    required: false
    default: 'latex-requirements.txt'
  install-ml-libs:
    description: 'Whether to install JAX/PyTorch with CUDA support'
    required: false
    default: 'false'
  ml-libs-version:
    description: 'Version tag for ML libraries cache key'
    required: false
    default: 'jax062-torch-nightly-cuda12'

outputs:
  container-mode:
    description: 'Whether running in container mode'
    value: ${{ steps.detect-container.outputs.container-mode }}
  conda-cache-hit:
    description: 'Whether conda cache was hit (non-container mode only)'
    value: ${{ steps.conda-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # Detect if running inside QuantEcon container
    - name: Detect container environment
      id: detect-container
      shell: bash
      run: |
        if [ -f "/etc/quantecon-container" ]; then
          echo "ðŸ³ Running inside QuantEcon container"
          echo "container-mode=true" >> $GITHUB_OUTPUT
          cat /etc/quantecon-container
        else
          echo "ðŸ“¦ Running on standard runner (non-container mode)"
          echo "container-mode=false" >> $GITHUB_OUTPUT
        fi

    # ============================================================
    # CONTAINER MODE: Only install delta packages from environment.yml
    # Cache the full conda environment prefix to avoid inconsistent state
    # ============================================================
    
    - name: Cache conda environment (container mode)
      if: steps.detect-container.outputs.container-mode == 'true' && inputs.environment-file != ''
      uses: actions/cache@v4
      id: container-pkg-cache
      with:
        path: |
          /opt/conda/envs/${{ inputs.environment-name }}
          /opt/conda/pkgs
        key: container-env-${{ hashFiles(inputs.environment-file) }}-${{ inputs.cache-version }}
        restore-keys: |
          container-env-${{ hashFiles(inputs.environment-file) }}-
          container-env-

    - name: Install lecture-specific packages (container mode)
      if: steps.detect-container.outputs.container-mode == 'true' && inputs.environment-file != '' && steps.container-pkg-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "::group::Installing lecture-specific packages"
        if [ -f "${{ inputs.environment-file }}" ]; then
          echo "Updating environment from ${{ inputs.environment-file }}"
          # Use conda env update WITHOUT --prune (prune causes full env solve which is slow)
          conda env update -n ${{ inputs.environment-name }} -f ${{ inputs.environment-file }}
          echo "âœ… Lecture packages installed"
        else
          echo "âš ï¸ Environment file not found: ${{ inputs.environment-file }}"
          echo "::error::Environment file not found: ${{ inputs.environment-file }}"
          exit 1
        fi
        echo "::endgroup::"
    
    - name: Container mode - no packages needed
      if: steps.detect-container.outputs.container-mode == 'true' && inputs.environment-file == ''
      shell: bash
      run: |
        echo "ðŸ³ Container mode with no environment file"
        echo "âœ… Using container's pre-installed packages (fastest path)"

    # ============================================================
    # NON-CONTAINER MODE: Full installation (existing behavior)
    # ============================================================
    
    - name: Cache Conda Environment (non-container mode)
      if: steps.detect-container.outputs.container-mode == 'false'
      uses: actions/cache@v4
      id: conda-cache
      with:
        path: |
          /home/runner/miniconda3/envs/${{ inputs.environment-name }}
          /home/runner/conda_pkgs_dir
        key: conda-${{ runner.os }}-${{ hashFiles(inputs.environment-file) }}-${{ inputs.cache-version }}
        restore-keys: |
          conda-${{ runner.os }}-${{ hashFiles(inputs.environment-file) }}-
          conda-${{ runner.os }}-
    
    - name: Setup Anaconda (non-container mode)
      if: steps.detect-container.outputs.container-mode == 'false'
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true
        miniconda-version: 'latest'
        python-version: ${{ inputs.python-version }}
        environment-file: ${{ inputs.environment-file }}
        activate-environment: ${{ inputs.environment-name }}
        use-only-tar-bz2: true

    - name: Install LaTeX packages (non-container mode)
      if: steps.detect-container.outputs.container-mode == 'false' && inputs.install-latex == 'true'
      shell: bash
      run: |
        if [ -f "${{ inputs.latex-requirements-file }}" ]; then
          echo "Reading packages from ${{ inputs.latex-requirements-file }}"
          PACKAGES=$(grep -v '^#' "${{ inputs.latex-requirements-file }}" | grep -v '^[[:space:]]*$' | tr '\n' ' ')
          echo "Installing LaTeX packages: $PACKAGES"
          sudo apt-get update
          sudo apt-get install -y $PACKAGES
        else
          echo "Warning: No latex-requirements.txt found at ${{ inputs.latex-requirements-file }}"
          echo "Skipping LaTeX installation"
        fi

    # ============================================================
    # ML LIBRARIES: Same for both modes
    # ============================================================
    
    - name: Cache pip packages (ML libs)
      uses: actions/cache@v4
      if: inputs.install-ml-libs == 'true'
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ inputs.ml-libs-version }}-${{ hashFiles(inputs.environment-file) }}-${{ inputs.cache-version }}
        restore-keys: |
          pip-${{ runner.os }}-${{ inputs.ml-libs-version }}-
          pip-${{ runner.os }}-

    - name: Install JAX, PyTorch, NumPyro, Pyro
      if: inputs.install-ml-libs == 'true'
      shell: bash -l {0}
      run: |
        echo "Installing ML libraries with CUDA support..."
        pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
        pip install pyro-ppl
        pip install --upgrade "jax[cuda12-local]==0.6.2"
        pip install numpyro
        echo "Testing JAX installation..."
        python scripts/test-jax-install.py || echo "JAX test script not found or failed (non-fatal)"

    # ============================================================
    # SUMMARY: Display environment info
    # ============================================================
        
    - name: Display Environment Info
      shell: bash
      run: |
        echo "::group::Environment Setup Summary"
        if [ "${{ steps.detect-container.outputs.container-mode }}" == "true" ]; then
          # Detect actual container image from marker file
          if [ -f /etc/quantecon-container ]; then
            CONTAINER_IMAGE=$(grep '^image=' /etc/quantecon-container | head -n 1 | cut -d'=' -f2-)
            if [ -z "$CONTAINER_IMAGE" ]; then
              CONTAINER_IMAGE="QuantEcon container"
            fi
          else
            CONTAINER_IMAGE="QuantEcon container"
          fi
          echo "ðŸ³ Mode: Container ($CONTAINER_IMAGE)"
          echo "   LaTeX: Pre-installed âœ…"
          echo "   Python: Pre-installed âœ…"
          echo "   Base packages: Pre-installed âœ…"
          if [ -n "${{ inputs.environment-file }}" ]; then
            if [ "${{ steps.container-pkg-cache.outputs.cache-hit }}" == "true" ]; then
              echo "   Lecture packages: Restored from cache âœ…"
            else
              echo "   Lecture packages: Installed from environment.yml"
            fi
          else
            echo "   Lecture packages: Not requested (no environment file)"
          fi
        else
          echo "ðŸ“¦ Mode: Standard runner"
          if [ "${{ steps.conda-cache.outputs.cache-hit }}" == "true" ]; then
            echo "   Conda: Restored from cache âœ… (saved ~5-6 minutes)"
          else
            echo "   Conda: Installed fresh"
          fi
          if [ "${{ inputs.install-latex }}" == "true" ]; then
            echo "   LaTeX: Installed"
          else
            echo "   LaTeX: Skipped"
          fi
        fi
        if [ "${{ inputs.install-ml-libs }}" == "true" ]; then
          echo "   ML Libraries: Installed (JAX, PyTorch)"
        fi
        echo "::endgroup::"
        
        echo "::group::Python packages"
        pip list 2>/dev/null || conda list
        echo "::endgroup::"
        
        echo "::group::LaTeX version"
        pdflatex --version 2>/dev/null || echo "pdfLaTeX not in PATH"
        echo "::endgroup::"

branding:
  icon: 'package'
  color: 'blue'
