name: 'Setup Environment'
description: 'Flexible environment setup - auto-detects container or installs Conda, LaTeX, and ML libraries'
author: 'QuantEcon'

inputs:
  python-version:
    description: 'Python version to use (ignored in container mode)'
    required: false
    default: '3.13'
  environment:
    description: 'Path to environment.yml for full environment (non-container builds)'
    required: false
    default: 'environment.yml'
  environment-update:
    description: 'Path to delta environment.yml for container builds (empty = use pre-installed packages only)'
    required: false
    default: ''
  environment-name:
    description: 'Conda environment name (must match name in environment.yml)'
    required: false
    default: 'quantecon'
  cache-version:
    description: 'Cache version for manual invalidation (bump to force cache rebuild)'
    required: false
    default: 'v1'
  install-latex:
    description: 'Whether to install LaTeX packages (auto-disabled in container mode)'
    required: false
    default: 'false'
  latex-requirements-file:
    description: 'Path to latex-requirements.txt file listing packages to install'
    required: false
    default: 'latex-requirements.txt'
  install-ml-libs:
    description: 'Whether to install JAX/PyTorch with CUDA support'
    required: false
    default: 'false'
  ml-libs-version:
    description: 'Version tag for ML libraries cache key'
    required: false
    default: 'jax062-torch-nightly-cuda12'

outputs:
  container-mode:
    description: 'Whether running in container mode'
    value: ${{ steps.detect-container.outputs.container-mode }}
  conda-cache-hit:
    description: 'Whether conda cache was hit (standard mode only, always false in container mode)'
    value: ${{ steps.conda-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # Detect if running inside QuantEcon container
    - name: Detect container environment
      id: detect-container
      shell: bash
      run: |
        if [ -f "/etc/quantecon-container" ]; then
          echo "ðŸ³ Running inside QuantEcon container"
          echo "container-mode=true" >> $GITHUB_OUTPUT
          cat /etc/quantecon-container
        else
          echo "ðŸ“¦ Running on standard runner (non-container mode)"
          echo "container-mode=false" >> $GITHUB_OUTPUT
        fi

    # ============================================================
    # CONTAINER MODE: Only install delta packages from environment.yml
    # Note: Conda environment caching is disabled in container mode because
    #       the Conda env lives outside the workspace mount, so actions/cache
    #       cannot persist it. Other host-mounted paths (e.g., pip cache) may
    #       still be cached.
    # See: https://github.com/QuantEcon/actions/issues/18
    # ============================================================

    - name: Update environment (container mode)
      if: steps.detect-container.outputs.container-mode == 'true' && inputs.environment-update != ''
      shell: bash
      run: |
        echo "::group::Environment Update (Container Mode)"
        echo "ðŸ“¦ Action: Installing delta packages from ${{ inputs.environment-update }}"
        if [ -f "${{ inputs.environment-update }}" ]; then
          echo "Running: conda env update -f ${{ inputs.environment-update }}"
          conda env update -f ${{ inputs.environment-update }}
          echo "âœ… Environment updated successfully"
        else
          echo "::error::Environment update file not found: ${{ inputs.environment-update }}"
          exit 1
        fi
        echo "::endgroup::"
    
    - name: Skip environment update (container mode)
      if: steps.detect-container.outputs.container-mode == 'true' && inputs.environment-update == ''
      shell: bash
      run: |
        echo "::group::Environment Setup (Container Mode)"
        echo "ðŸ³ Action: Using pre-installed container packages"
        echo "â„¹ï¸  No environment-update file specified - skipping conda env update"
        echo "âœ… Ready to build (fastest path)"
        echo "::endgroup::"

    # ============================================================
    # NON-CONTAINER MODE: Full installation (existing behavior)
    # ============================================================
    
    - name: Cache Conda Environment (non-container mode)
      if: steps.detect-container.outputs.container-mode == 'false'
      uses: actions/cache@v4
      id: conda-cache
      with:
        path: |
          /home/runner/miniconda3/envs/${{ inputs.environment-name }}
          /home/runner/conda_pkgs_dir
        key: conda-${{ runner.os }}-${{ hashFiles(inputs.environment) }}-${{ inputs.cache-version }}
        restore-keys: |
          conda-${{ runner.os }}-${{ hashFiles(inputs.environment) }}-
          conda-${{ runner.os }}-
    
    - name: Setup Anaconda (non-container mode)
      if: steps.detect-container.outputs.container-mode == 'false'
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true
        miniconda-version: 'latest'
        python-version: ${{ inputs.python-version }}
        environment-file: ${{ inputs.environment }}
        activate-environment: ${{ inputs.environment-name }}
        use-only-tar-bz2: true

    - name: Install LaTeX packages (non-container mode)
      if: steps.detect-container.outputs.container-mode == 'false' && inputs.install-latex == 'true'
      shell: bash
      run: |
        if [ -f "${{ inputs.latex-requirements-file }}" ]; then
          echo "Reading packages from ${{ inputs.latex-requirements-file }}"
          PACKAGES=$(grep -v '^#' "${{ inputs.latex-requirements-file }}" | grep -v '^[[:space:]]*$' | tr '\n' ' ')
          echo "Installing LaTeX packages: $PACKAGES"
          sudo apt-get update
          sudo apt-get install -y $PACKAGES
        else
          echo "Warning: No latex-requirements.txt found at ${{ inputs.latex-requirements-file }}"
          echo "Skipping LaTeX installation"
        fi

    # ============================================================
    # ML LIBRARIES: Same for both modes
    # ============================================================
    
    - name: Cache pip packages (ML libs)
      uses: actions/cache@v4
      if: inputs.install-ml-libs == 'true'
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ inputs.ml-libs-version }}-${{ hashFiles(inputs.environment) }}-${{ inputs.cache-version }}
        restore-keys: |
          pip-${{ runner.os }}-${{ inputs.ml-libs-version }}-
          pip-${{ runner.os }}-

    - name: Install JAX, PyTorch, NumPyro, Pyro
      if: inputs.install-ml-libs == 'true'
      shell: bash -l {0}
      run: |
        echo "Installing ML libraries with CUDA support..."
        pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
        pip install pyro-ppl
        pip install --upgrade "jax[cuda12-local]==0.6.2"
        pip install numpyro
        echo "Testing JAX installation..."
        python scripts/test-jax-install.py || echo "JAX test script not found or failed (non-fatal)"

    # ============================================================
    # SUMMARY: Display environment info
    # ============================================================
        
    - name: Display Environment Info
      # Use plain bash to avoid login shell PATH reset in containers
      # (Ubuntu's /etc/profile can drop /opt/conda from PATH)
      shell: bash
      run: |
        echo "::group::Environment Setup Summary"
        if [ "${{ steps.detect-container.outputs.container-mode }}" == "true" ]; then
          # Detect actual container image from marker file
          if [ -f /etc/quantecon-container ]; then
            CONTAINER_IMAGE=$(grep '^image=' /etc/quantecon-container | head -n 1 | cut -d'=' -f2-)
            if [ -z "$CONTAINER_IMAGE" ]; then
              CONTAINER_IMAGE="QuantEcon container"
            fi
          else
            CONTAINER_IMAGE="QuantEcon container"
          fi
          echo "ðŸ³ Mode: Container ($CONTAINER_IMAGE)"
          echo "   LaTeX: Pre-installed âœ…"
          echo "   Python: Pre-installed âœ…"
          echo "   Base packages: Pre-installed âœ…"
          if [ -n "${{ inputs.environment-update }}" ]; then
            echo "   Environment update: Applied from ${{ inputs.environment-update }}"
          else
            echo "   Environment update: Skipped (using pre-installed packages)"
          fi
        else
          echo "ðŸ“¦ Mode: Standard runner"
          if [ "${{ steps.conda-cache.outputs.cache-hit }}" == "true" ]; then
            echo "   Conda: Restored from cache âœ… (saved ~5-6 minutes)"
          else
            echo "   Conda: Installed fresh"
          fi
          if [ "${{ inputs.install-latex }}" == "true" ]; then
            echo "   LaTeX: Installed"
          else
            echo "   LaTeX: Skipped"
          fi
        fi
        if [ "${{ inputs.install-ml-libs }}" == "true" ]; then
          echo "   ML Libraries: Installed (JAX, PyTorch)"
        fi
        echo "::endgroup::"
        
        echo "::group::Python packages"
        pip list 2>/dev/null || conda list
        echo "::endgroup::"
        
        echo "::group::LaTeX version"
        pdflatex --version 2>/dev/null || echo "pdfLaTeX not in PATH"
        echo "::endgroup::"

branding:
  icon: 'package'
  color: 'blue'
