name: 'Setup QuantEcon Lecture Environment'
description: 'Sets up Conda environment with Python, pip packages, and optional ML libraries with intelligent caching'
author: 'QuantEcon'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  environment-file:
    description: 'Path to environment.yml'
    required: false
    default: 'environment.yml'
  environment-name:
    description: 'Conda environment name (must match name in environment.yml)'
    required: false
    default: 'quantecon'
  cache-version:
    description: 'Cache version for manual invalidation (bump to force cache rebuild)'
    required: false
    default: 'v1'
  install-ml-libs:
    description: 'Whether to install JAX/PyTorch with CUDA support'
    required: false
    default: 'false'
  ml-libs-version:
    description: 'Version tag for ML libraries cache key (update when changing JAX/PyTorch versions)'
    required: false
    default: 'jax062-torch-nightly-cuda12'

runs:
  using: "composite"
  steps:
    - name: Setup Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true
        miniconda-version: 'latest'
        python-version: ${{ inputs.python-version }}
        environment-file: ${{ inputs.environment-file }}
        activate-environment: ${{ inputs.environment-name }}

    - name: Cache Conda Environment
      uses: actions/cache@v4
      id: conda-cache
      with:
        path: |
          /usr/share/miniconda/envs/${{ inputs.environment-name }}
          ~/.conda/pkgs
        key: conda-${{ runner.os }}-${{ hashFiles(inputs.environment-file) }}-${{ inputs.cache-version }}
        restore-keys: |
          conda-${{ runner.os }}-${{ hashFiles(inputs.environment-file) }}-
          conda-${{ runner.os }}-

    - name: Cache pip packages
      uses: actions/cache@v4
      if: inputs.install-ml-libs == 'true'
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ inputs.ml-libs-version }}-${{ hashFiles(inputs.environment-file) }}-${{ inputs.cache-version }}
        restore-keys: |
          pip-${{ runner.os }}-${{ inputs.ml-libs-version }}-
          pip-${{ runner.os }}-

    - name: Install JAX, PyTorch, NumPyro, Pyro
      if: inputs.install-ml-libs == 'true'
      shell: bash -l {0}
      run: |
        echo "Installing ML libraries with CUDA support..."
        pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
        pip install pyro-ppl
        pip install --upgrade "jax[cuda12-local]==0.6.2"
        pip install numpyro
        echo "Testing JAX installation..."
        python scripts/test-jax-install.py || echo "JAX test script not found or failed (non-fatal)"
        
    - name: Display Conda Environment Info
      shell: bash -l {0}
      run: |
        echo "::group::Conda packages"
        conda list
        echo "::endgroup::"
        echo "::group::Pip packages"
        pip list
        echo "::endgroup::"
        echo "::group::Cache status"
        echo "Conda cache hit: ${{ steps.conda-cache.outputs.cache-hit }}"
        echo "Pip cache hit: ${{ steps.pip-cache.outputs.cache-hit }}"
        echo "::endgroup::"

branding:
  icon: 'package'
  color: 'blue'
