name: 'Publish to GitHub Pages'
description: 'Publishes lecture builds to GitHub Pages with intelligent caching and artifact management'
author: 'QuantEcon'

inputs:
  build-dir:
    description: 'Directory containing built site'
    required: true
  github-token:
    description: 'GitHub token for deployment (use secrets.GITHUB_TOKEN)'
    required: true
  target-branch:
    description: 'Branch to deploy to'
    required: false
    default: 'gh-pages'
  cname:
    description: 'Custom domain for GitHub Pages'
    required: false
    default: ''
  force-orphan:
    description: 'Force orphan branch (no history)'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for deployment'
    required: false
    default: 'Deploy to GitHub Pages'

outputs:
  page-url:
    description: 'URL of the deployed GitHub Pages site'
    value: ${{ steps.deploy.outputs.page-url }}

runs:
  using: "composite"
  steps:
    - name: Prepare build directory
      id: prepare
      shell: bash
      run: |
        echo "Preparing build directory: ${{ inputs.build-dir }}"
        
        # Verify build directory exists
        if [ ! -d "${{ inputs.build-dir }}" ]; then
          echo "❌ Error: Build directory not found: ${{ inputs.build-dir }}"
          exit 1
        fi
        
        # Count files
        FILE_COUNT=$(find "${{ inputs.build-dir }}" -type f | wc -l)
        echo "📊 Files to deploy: $FILE_COUNT"
        
        # Calculate size
        SIZE=$(du -sh "${{ inputs.build-dir }}" | cut -f1)
        echo "💾 Total size: $SIZE"
        
        # Add CNAME file if specified
        if [ -n "${{ inputs.cname }}" ]; then
          echo "${{ inputs.cname }}" > "${{ inputs.build-dir }}/CNAME"
          echo "🌐 Added CNAME: ${{ inputs.cname }}"
        fi
        
        echo "✅ Preparation complete"

    - name: Deploy to GitHub Pages
      id: deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.build-dir }}
        publish_branch: ${{ inputs.target-branch }}
        force_orphan: ${{ inputs.force-orphan }}
        commit_message: ${{ inputs.commit-message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Generate Page URL
      id: page-url
      shell: bash
      run: |
        if [ -n "${{ inputs.cname }}" ]; then
          PAGE_URL="https://${{ inputs.cname }}"
        else
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          OWNER_NAME="${GITHUB_REPOSITORY%/*}"
          PAGE_URL="https://${OWNER_NAME}.github.io/${REPO_NAME}"
        fi
        
        echo "page-url=$PAGE_URL" >> $GITHUB_OUTPUT
        echo "✅ Deployment successful!"
        echo "📍 Page URL: $PAGE_URL"

    - name: Display Deployment Info
      shell: bash
      run: |
        echo "::group::Deployment Summary"
        echo "Target branch: ${{ inputs.target-branch }}"
        echo "Custom domain: ${{ inputs.cname || 'None' }}"
        echo "Force orphan: ${{ inputs.force-orphan }}"
        echo "Page URL: ${{ steps.page-url.outputs.page-url }}"
        echo "::endgroup::"

branding:
  icon: 'globe'
  color: 'blue'
